// client/components/Header.vue
<template>
  <div class="w-screen bg-white h-20 flex items-center justify-between px-2 lg:px-20">
    <NuxtLink to="/" class="flex space-x-2">
      <img src="/logo.png" alt="logo" class="h-[30px]" />
      <p class="font-bold text-common text-3xl">ピ</p>
    </NuxtLink>

    <div class="flex space-x-2">
      <NuxtLink to="/signin" class="border py-2.5 px-4 rounded-md font-semibold hover:bg-gray-50">
        ログイン
      </NuxtLink>

      <NuxtLink to="/signup" class="border py-2.5 px-4 rounded-md font-semibold text-white bg-common hover:bg-common/90 ">
        はじめはしょう
      </NuxtLink>
    </div>
  </div>
</template>

<script setup lang="ts">

</script>

// web/components/header.tsx
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

export default function Header() {
  return (
    <div className='w-full h-20 bg-white md:px-32 px-2 flex items-center justify-between'>
      <div className='flex items-center space-x-2'>
        <Image src='/logo.png' width={1000} height={1000} className='w-[30px]' alt='logo' />
        <Link href={'/'} className='font-semibold text-3xl text-[#4a3aff]'>prg</Link>
      </div>

      <div className='flex items-center space-x-3'>
        <Link href='/sign-in' className='border px-5 py-2.5 flex rounded-xl hover:bg-gray-50'>
          ログイン
        </Link>

        <Link href='sign-up' className='border px-5 py-2.5 bg-[#4a3aff] hover:bg-[#4a3aff]/95 text-white flex rounded-xl'>
          始めましょう
        </Link>
      </div>
    </div>
  )
}
