// web/app/(auth)/sign-up/page.tsx
'use client';

import { SIGNUP_URL } from '@/lib/apiEndPoints';
import axios from '@/lib/axios';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import React, { useState } from 'react'
import { SubmitHandler, useForm } from 'react-hook-form';
import { FaLock, FaUser } from 'react-icons/fa';
import { IoMdEye, IoMdEyeOff } from 'react-icons/io';
import { LuLoader } from 'react-icons/lu';

type Inputs = {
  username: string;
  email: string;
  password: string;
}

export default function SignUp() {

  const [showPass, setShowPass] = useState(false);

  const { register, handleSubmit } = useForm<Inputs>()
  const [userError, setUserError] = useState('');
  const [emailError, setEmailError] = useState('');
  const [passwordError, setPasswordError] = useState('');
  const [loading, setLoading] = useState(false);

  const router = useRouter();

  const toggleShowPass = () => {
    if (showPass) setShowPass(false);
    else setShowPass(true);
  }

  const onSubmit: SubmitHandler<Inputs> = async (formData) => {

    if (formData.username.length === 0) {
      setUserError('ユーサー名を入力してください')
      return;
    } else {
      setUserError('');
    }

    if (formData.email.length === 0) {
      setEmailError('メールアドレスを入力してください');
      return;
    } else if (!/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(formData.email)) {
      setEmailError('無効なメールアドレス');
      return;
    } else {
      setEmailError('');
    }

    if (formData.password.length === 0) {
      setPasswordError('パスワードを入力してください');
      return;
    } else if (formData.password.length < 8) {
      setPasswordError('Password must be at least 8 characters');
      return;
    } else {
      setPasswordError('');
    }

    setLoading(true);
    
    await axios.post(SIGNUP_URL, formData);

    setLoading(false);

    router.push('/');
  }

  return (
    <div className='h-screen w-screen bg-[#fafafc] flex items-center justify-center'>
      <div className='w-full fixed top-0 h-20 bg-white md:px-32 px-2 flex items-center justify-between'>
        <div className='flex items-center space-x-2'>
          <Image src='/logo.png' width={1000} height={1000} className='w-[30px]' alt='logo' />
          <Link href={'/'} className='font-semibold text-3xl text-[#4a3aff]'>prg</Link>
        </div>
      </div>
      <div className='w-[450px] rounded-xl md:shadow-2xl bg-white p-10 flex flex-col justify-center'>
        <p className='font-bold text-3xl text-center mb-5'>登録</p>

        <form className='space-y-1'>
          <div className='relative text-[#4a3aff]'>
            <p className='font-semibold text-black'>ユーサー名</p>
            <FaUser size={20} className='absolute top-[37.5px] left-3' />
            <input type="email" placeholder='桐生戦兎' {...register('username')}
              className={`py-3 px-10 w-full text-black border-[1.5px] rounded focus:outline-none 
                ${userError ? 'border-rose-500' : 'focus:border-[#4a3aff]'}`}
            />
            <p className='text-rose-500 text-sm h-5'>{userError}</p>
          </div>

          <div className='relative text-[#4a3aff]'>
            <p className='font-semibold text-black'>メールアドレス</p>
            <FaUser size={20} className='absolute top-[37.5px] left-3' />
            <input type="email" placeholder='example@prg.co.jp' {...register('email')}
              className={`py-3 px-10 w-full text-black border-[1.5px] rounded focus:outline-none 
                ${emailError ? 'border-rose-500' : 'focus:border-[#4a3aff]'}`}
            />
            <p className='text-rose-500 text-sm h-5'>{emailError}</p>
          </div>

          <div className='relative text-[#4a3aff]'>
            <p className='font-semibold text-black'>パスワード</p>
            <FaLock size={20} className='absolute top-[37.5px] left-3' />
            <input type={showPass ? 'text' : 'password'} placeholder='パスワード' {...register('password')}
              className={`py-3 px-10 w-full text-black border-[1.5px] rounded focus:outline-none 
              ${passwordError ? 'border-rose-500' : 'focus:border-[#4a3aff]'}`}
            />
            {showPass ? <IoMdEye size={25} className='absolute top-[37.5px] right-3 cursor-pointer' onClick={() => toggleShowPass()} /> :
             <IoMdEyeOff size={25} className='absolute top-[38px] right-3 cursor-pointer' onClick={() => toggleShowPass()} /> 
            }
            <p className='text-rose-500 text-sm h-5'>{passwordError}</p>
          </div>

          <button onClick={handleSubmit(onSubmit)} className='w-full bg-[#4a3aff] text-white flex items-center justify-center rounded py-3'>
            {loading ? (
              <LuLoader size={24} className=' animate-spin' />
            ) : (
              <p className='font-semibold'>登録</p>
            )}
          </button>
        </form>  

        <div className='w-full h-[1px] bg-gray-300 my-5'></div>

        <div className='flex items-center justify-center cursor-pointer border rounded p-2 space-x-1 hover:bg-gray-50'>
          <Image src='/google.png' alt='googlelogo' width={2000} height={2000} className='w-[16px]' />
          <p className='font-semibold'>グーグルでログイン</p>
        </div>

        <Link href={'/sign-in'} className='text-center font-bold hover:underline mt-5'>ログイン</Link>
      </div>
    </div>
  )
}

// client/pages/signup.vue
<template>
  <div class="h-screen w-screen bg-[#fafafc] flex items-center justify-center">
    <div  iv class="w-[450px] md:bg-white md:shadow-md md:border rounded-xl p-8">
      <p class="text-center font-bold text-3xl">登録</p>

      <form class="my-5">
        <div class="w-full relative">
          <span class="font-semibold">ユーサー名</span>
          <Icon name="ic:round-person" size="24" class="absolute top-[37px] left-2 text-primary" />
          <input type="text" class="w-full border-2 px-10 py-2.5 rounded-md outline-none" 
            :class="nameError ? 'border-rose-500' : 'focus:border-common'" placeholder="" v-model="name"
          >
          <p class="text-rose-500 h-4 text-xs pt-0.5 font-semibold">{{ nameError }}</p>
        </div>

        <div class="w-full relative mt-3">
          <span class="font-semibold">メールアドレス</span>
          <Icon name="material-symbols:mail-rounded" size="24" class="absolute top-[37px] left-2 text-primary" />
          <input type="text" class="w-full border-2 px-10 py-2.5 rounded-md outline-none" 
            :class="emailError ? 'border-rose-500' : 'focus:border-common'" placeholder="example@prg.co.jp" v-model="email"
          >
          <p class="text-rose-500 h-4 text-xs pt-0.5 font-semibold">{{ emailError }}</p>
        </div>

        <div class="w-full relative my-3">
          <span class="font-semibold">パスワード</span>
          <Icon :name="showPassword ? 'material-symbols:lock-open-right-rounded' : 'material-symbols:lock'" size="24" class="absolute top-[37px] left-2 text-primary" />
          <Icon @click="toggleShowPassword()" :name="showPassword ? 'mdi:eye' : 'mdi:eye-off'" 
            size="20" class="absolute top-[40px] right-3 text-primary cursor-pointer" 
          />
          <input :type="showPassword ? 'text' : 'password'" class="w-full border-2 px-10 py-2.5 rounded-md outline-none" 
            :class="passwordError ? 'border-rose-500' : 'focus:border-common'" v-model="password"
          >
          <p class="text-rose-500 h-4 text-xs py-0.5 font-semibold">{{ passwordError }}</p>
        </div>

        <Select v-model="role">
          <SelectTrigger>
            <SelectValue placeholder="教師" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectItem value="teacher">教師</SelectItem>
              <SelectItem value="student">生徒</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>

        <Button @click="signup()" class="bg-common w-full hover:bg-common/90 py-6 mt-5">
          <Icon v-if="isLoading"name="icon-park-outline:loading-four" size="24" class="animate-spin"/>
          <p v-else>登録</p>
        </Button>
      </form>

      <div class="h-4 text-center text-xs pt-1 text-rose-500 font-semibold">{{ serverError }}</div>

      <Button class="w-full flex items-center justify-center py-6 border bg-white hover:bg-gray-50 space-x-1">
        <img src="/google.png" alt="google" class="w-[24px]">
        <p class="text-black">グーグルでログイン</p>
      </Button>

      <div class="w-full text-center mt-3">
        <NuxtLink to="/signin" class=" font-semibold hover:underline">ログイン</NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ middleware: 'is-logged-in' });

import { Button } from '@/components/ui/button';
import { Icon } from '#components';
import axiosClient from '~/lib/axios';
import { useUserStore } from '~/stores/user';

import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

let name = ref('');
let email = ref('');
let password = ref('');
let role = ref('teacher');
let nameError = ref('');
let emailError = ref('');
let passwordError = ref('');
let serverError = ref('');
let showPassword = ref(false);
let isLoading = ref(false);

const router = useRouter();
const store = useUserStore();

const toggleShowPassword = () => {
  if (showPassword.value) showPassword.value = false;
  else showPassword.value = true;
}

watch(() => email.value, () => serverError.value = '');

watch(() => password.value, () => serverError.value = '');


const signup = async () => {
  if (!name.value) {
    nameError.value = 'ユーサー名を入力してきださい。';
    return;
  } else {
    nameError.value = '';
  }

  if (!email.value) {
    emailError.value = 'メールアドレスを入力してきださい。'
    return;
  } else if(!/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(email.value)) {
    emailError.value = '無効なメールアドレス。';
    return;
  } else {
    emailError.value = '';
  }

  if (!password.value) {
    passwordError.value = 'パスワードを入力してきださい。';
    return;
  } else if (password.value.length < 8) {
    passwordError.value = 'パスワードは8文字以上でなければなりません。';
    return;
  } else {
    passwordError.value = '';
  }

  isLoading.value = true;

  await axiosClient.get('/sanctum/csrf-cookie');

  await axiosClient.post('/register', { 
    name: name.value, 
    email: email.value, 
    password: password.value,
    role: role.value
  }).then( async res => {
    const user = (await axiosClient.get('/api/user')).data;
    store.user = user;
    router.push('/dashboard');
  }).catch(err => {
    serverError.value = 'ユーザーが登録されました。';
  }).finally(() => {
    isLoading.value = false;
  });
}

</script>
