// client/src/components/sidebar/left-sidebar.tsx
'use client';
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation';
import React, { useEffect, useState } from 'react'
import { GoHomeFill } from "react-icons/go";
import { GrTest } from 'react-icons/gr';
import Icon from '../icon';
import { PiSignOutBold } from "react-icons/pi";
import { IoMdSettings } from "react-icons/io";
import axiosClient from '@/lib/axios';
import { useUser } from '@/hooks/useUser';
import { useCookies } from 'react-cookie';

import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { LuLoader2 } from 'react-icons/lu';

export default function LeftSidebar() {

  const sidebarItem = [
    {
      icon: GoHomeFill,
      name: 'ダッシュボード',
      link: '/dashboard'
    },
    {
      icon: GrTest,
      name: 'テスト',
      link: '/dashboard/exam'
    },
  ];

  const pathname = usePathname();
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [cookies, setCookie, removeCookie] = useCookies(['XSRF-TOKEN', 'laravel_session']);

  const { user, setUser } = useUser();

  const signout = async () => {
    setLoading(true);
    await axiosClient.post('/logout');
    setUser(null);
    router.push('/signin');
    removeCookie('XSRF-TOKEN');
    removeCookie('laravel_session');
    setLoading(false);
  }


  return (
    <div className='w-[300px] h-full bg-[#4a3aff] rounded-r-xl py-10'>
      <div className='flex flex-col justify-between h-full'>
        <div className='flex flex-col space-y-5'>
          {sidebarItem.map((item, index) => (
            <Link href={item.link} key={index} className='h-[50px]'>
              <div className='flex items-center h-full w-full'>
                <span className={`h-full w-1 rounded-r-xl ${item.link === pathname && 'bg-white'}`} />

                <div className={`flex px-5 items-center space-x-3 ${item.link === pathname ? 'text-white' : 'text-white'}`}>
                  <Icon size={24} icon={item.icon} className='' />
                  <p>{item.name}</p>
                </div>
              </div>
            </Link>
          ))}
        </div>

        <div className='flex flex-col space-y-5'>
          <div className='flex items-center w-full px-5 space-x-3 text-white'>
            <IoMdSettings size={24} />
            <p>設定</p>
          </div>

          <Dialog>
            <DialogTrigger className='flex items-center w-full px-5 space-x-3 text-white'>
              <PiSignOutBold size={24} />
              <p>ログアウト</p>
            </DialogTrigger>

            <DialogContent>
              <DialogHeader>
                <DialogTitle>本当にサインアウトしますか?</DialogTitle>
              </DialogHeader>

              <DialogFooter className="flex justify-start font-semibold">
                <DialogClose asChild>
                  <button className='border w-[120px] border-[#4a3aff] text-[#4a3aff] py-2 rounded-md'>
                    閉じる  
                  </button>
                </DialogClose>

                <button onClick={() => signout()} className='bg-[#4a3aff] w-[120px] text-white py-2 rounded-md flex items-center justify-center'>
                  {loading ? (
                    <LuLoader2 size={24} className=' animate-spin' />
                  ) : (
                    <p>
                      ログアウト
                    </p>
                  )}
                </button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>
    </div>
  )
}

// client/components/LeftSidebar.vue
<template>
  <div class="w-[250px] h-full bg-common flex flex-col justify-between py-5">
    <div class="flex flex-col space-y-3">
      <NuxtLink to="/dashboard" class="px-5 py-3 font-semibold text-white relative flex items-center">
        <div v-if="route.path === '/dashboard'" class="h-full w-1 rounded-r-md bg-white absolute left-0" />
        ダッシュボード
      </NuxtLink>

      <NuxtLink to="/dashboard/exam" class="px-5 py-3 font-semibold text-white relative flex items-center">
        <div v-if="route.path === '/dashboard/exam'" class="h-full w-1 rounded-r-md bg-white absolute left-0" />
        テスト
      </NuxtLink>
    </div>

    <div class="w-full px-5">
      <Button class="bg-transparent text-white px-5 text-base hover:bg-transparent">
        <Dialog>
          <DialogTrigger class="flex items-center justify-start space-x-2">
            <Icon name="material-symbols:logout-rounded" size="24" />
            <p>ログアウト</p>
          </DialogTrigger>

          <DialogContent>
            <DialogHeader>
              <DialogTitle class="text-center font-bold text-2xl mb-2">ログアウト</DialogTitle>
              <DialogDescription class="text-center text-base">
                本当にログアウトしてもよろしいですか？
              </DialogDescription>
            </DialogHeader>

            <DialogFooter>
              <DialogClose class="border py-2 px-3 rounded-md hover:bg-gray-50 font-semibold">
                閉じる
              </DialogClose>

              <Button class="w-[100px]" @click="logout()">
                <Icon v-if="isLoading" name="icon-park-outline:loading-four" size="20" class="animate-spin" />
                <p v-else>ログアウト</p>
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Button } from './ui/button';
import { Icon } from '#components';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger, DialogClose } from '@/components/ui/dialog'
import axiosClient from '~/lib/axios';
const token = useCookie('XSRF-TOKEN');

let isLoading = ref(false);

const route = useRoute();
const router = useRouter();

const logout = async () => {
  isLoading.value = true;
  await axiosClient.post('/logout');
  token.value = null;
  isLoading.value = false;
  router.push('/signin');
}


</script>
